name: Staging Environment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

env:
  AZURE_WEB_APP_NAME: cheese-itf
  AZURE_RESOURCE_GROUP_NAME: spino-cap

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: copy publish files
      run: |
        mkdir publish
        cp -r .nuxt server static nuxt.config.ts package*.json publish/

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: staging
        path: publish

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://${{ env.AZURE_WEB_APP_NAME }}-pr-${{ github.event.number }}.azurewebsites.net
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: staging

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm ci for production
      run: |
        ls -la
        npm ci --production

    - name: Deploy staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        slot-name: pr-${{ github.event.number }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_874AF7C691714B0EB899EB72B98251C3 }}
        package: .
